name: Update Map

on:
  push:
    branches: [main]
    paths:
      - "Root_Node_Example/**" # Rename to your actual root path name
      - "meta.json"
  workflow_dispatch:

jobs:
  update-fli-map:
    runs-on: ubuntu-latest
    steps:
      - name: Call conversion endpoint
        run: |
          curl -X POST https://www.airesearchmaps.com/api/update_map \
          -H "Content-Type: application/json" \
          -H "API_KEY: ${{ secrets.UPDATE_MAP_KEY }}" \
          -d '{
            "map_repo": "${{ github.repository }}"
          }'
